### ISSUE TITLE
Reproducing results on proteins

### ISSUE THREAD

**Issue by kaansancak** [qitianwu/SGFormer#11]
Hi,

I run the following command to reproduce ogbn-proteins results

```
python main-batch.py --method sgformer  --dataset ogbn-proteins --metric rocauc --lr 0.01 --hidden_channels 64 \
    --gnn_num_layers 2  --gnn_dropout 0. --gnn_weight_decay 0. --gnn_use_residual --gnn_use_weight --gnn_use_bn --gnn_use_act \
    --trans_num_layers 1 --trans_dropout 0. --trans_weight_decay 0. --trans_use_residual --trans_use_weight --trans_use_bn \
    --use_graph --graph_weight 0.5 \
    --batch_size 10000 --seed 123 --runs 5 --epochs 1000 --eval_step 9 --device 1
```

This is the accuracy I am getting:

`Chosen epoch: 65 Final Train: 81.17 Final Test: 72.85.`

I haven't gotten all 5 runs because it seems very far away from the reported number.

Is the command provided in the `run.sh` right?

**Comment by qitianwu** [comment]
Hi, the reason can be that you use an inconsistent PyG version (e.g., 2.0+) as what we used (1.7.2). The `subgraph` is implemented in different ways, where the `relabel_nodes` in `subgraph` (used in [main-batch.py](https://github.com/qitianwu/SGFormer/blob/7034dfd5349be49f2bcb2e96cbc37762d7c0466a/large/main-batch.py#L139C13-L139C91)) will reorder the node index for 1.7.2 but not for 2.0+. 

More details about this can be found in the [Issue #7 of NodeFormer](https://github.com/qitianwu/NodeFormer/issues/7)

**Comment by kaansancak** [comment]
Thanks!
