### ISSUE TITLE
PyG version >= 2.x required for papers100m

### ISSUE THREAD

**Issue by kaansancak** [qitianwu/SGFormer#13]
It appears that the loader for papers100m is utilizing NeighborLoader (https://github.com/qitianwu/SGFormer/blob/main/100M/nb-sample.py#L16), which is accessible after PyG >= 2.x, as indicated in https://github.com/pyg-team/pytorch_geometric/issues/3868.

The code fails to execute with the requirements.txt specified in /large.

I resolved this issue on my end by upgrading PyG. However, it would be appreciated if you could provide the versions you used for this experiment.

**Comment by qitianwu** [comment]
Thanks. For papers100M, we used PyG version >= 2.0, but we cannot log in to the machine we used for experiments at this point. Given this situation, we cannot figure out the specific environment. That being said, according to our experiences, the PyG version makes little difference to the performance on this large dataset.

Sorry for the late response and hope this information is helpful.

**Comment by kaansancak** [comment]
Can you provide some guidelines to run papers100m? Simply using pyg 2.0 with compatible packages does not seems to work for me.
