### ISSUE TITLE
Why is it that only GCN achieves about 84.9% of the results, but only 84% when attention is added?

### ISSUE THREAD

**Issue by CharliedoD** [qitianwu/SGFormer#14]
![1715856303417](https://github.com/qitianwu/SGFormer/assets/117720770/5048f689-03b9-4f8c-ac3f-0fee883bb683)
![image](https://github.com/qitianwu/SGFormer/assets/117720770/28227de4-6fad-4240-87f8-c6bc925f0bd0)

**Comment by qitianwu** [comment]
Hi, we use the Final Test (testing score achieved by the epoch with the highest valid score) for all the reported results in the paper. The Highest Test is not used for comparison since it requires testing data
