### ISSUE TITLE
About Proof for Theorem 2

### ISSUE THREAD

**Issue by yizhihenpidehou** [qitianwu/SGFormer#15]
Hi~ I'm not very good at maths, I want to ask about the proof of (18) in the appendix of the paper.
![80a92737f7ec4704f948b2b9c21e96ff](https://github.com/qitianwu/SGFormer/assets/61486008/ce996990-98dd-4168-8d4f-f227c89504f1)

**Comment by qitianwu** [comment]
第一步是由后面一项得到，第二步是因为attention score加起来等于1
