### ISSUE TITLE
可以求一份 PPT 吗？

### ISSUE THREAD

**Issue by xioacd99** [qitianwu/SGFormer#16]
昨晚刷到了大神的三篇工作，NodeFormer，DIFFormer 和 SGFormer，感觉真的是一个非常好的工作，三篇工作能够圈起来成为一个圈，还是逐步递进的，B 站上看到大神的讲解视频，PPT 做的也是很棒，github 链接过期了，请问可以更新一份这三篇工作的 PPT 吗？😶‍🌫️

**Comment by qitianwu** [comment]
已上传到github repo

10分钟介绍的slides: https://github.com/qitianwu/SGFormer/blob/main/sgformer-slides.pdf

更详细的介绍三个工作的slides: https://github.com/qitianwu/SGFormer/blob/main/GT_slides.pdf
