### ISSUE TITLE
Running Papers100M

### ISSUE THREAD

**Issue by kaansancak** [qitianwu/SGFormer#17]
Can you provide some guidelines to run papers100m? Simply using pyg 2.0 with compatible packages does not seems to work for me.

_Originally posted by @kaansancak in https://github.com/qitianwu/SGFormer/issues/13#issuecomment-2187429009_

**Comment by qitianwu** [comment]
For papers100, you may need a machine with CPU memory more than 400GB. The PyG version >= 2.0 should normally work.
