### ISSUE TITLE
GN Block Impact on SGFormer Performance

### ISSUE THREAD

**Issue by FeiGSSS** [qitianwu/SGFormer#5]
Hello Qitian,

Firstly, I would like to express my appreciation for your inspiring work and the dedication evident in your code! My primary interest lies in understanding how the GN block influences the performance of SGFormer. To this end, I adjusted the `graph_weight` parameter within the range of `[0, 0.5, 0.8, 1.0]` and conducted experiments on medium-sized benchmarks. Below, I present both the reproduced results and those reported in your paper.
<img width="732" alt="截屏2023-12-26 22 36 12" src="https://github.com/qitianwu/SGFormer/assets/29545851/b4d9b9a0-bbac-40ac-8d3a-3a9585ee55c4">

Observations and Questions:
1. Overall, I am quite satisfied as I achieved similar or nearly identical performance to what was reported in the paper for most datasets. However, there were some exceptions: notably lower results in the squirrel dataset and an unexpectedly higher score in chameleon. Could you please shed some light on why this might be the case?
2. Furthermore, when setting the `graph_weight` to 1, SGFormer essentially transformed into a simple GCN model. In this scenario, the performance of the GCN model significantly surpassed what was reported in your paper, especially in the datasets cora, citeseer, pubmed, and squirrel. This observation seems to diminish the relative improvements of SGFormer over the standard GCN model.

Reproducing Data & Environment:
- I used datasets and splittings from the provided shared link.
- The following are details of my environment setup:
   - python=3.8.18=h955ad1f_0
   - pytorch=2.1.1=py3.8_cuda11.8_cudnn8.7.0_0
   - pytorch-cluster=1.6.3=py38_torch_2.1.0_cu118

   - pytorch-scatter=2.1.2=py38_torch_2.1.0_cu118
   - pytorch-sparse=0.6.18=py38_torch_2.1.0_cu118

Your insights or suggestions regarding these observations would be highly valuable.

**Comment by qitianwu** [comment]
Hi, thanks for your interest in our work. For the chameleon and squirrel datasets, you need to use the new splits from 

https://github.com/yandex-research/heterophilous-graphs/tree/main

The results you currently obtain should be based on the original splits (the ones in the provided google drive) that have overlapping data in the training and testing sets.
